# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: omec-project/.github/.github/workflows/build.yml@main
    with:
      branch_name: ${{ github.ref }}

  docker-build:
    uses: omec-project/.github/.github/workflows/docker-build.yml@main
    with:
      branch_name: ${{ github.ref }}

  static-analysis:
    uses: omec-project/.github/.github/workflows/static-analysis.yml@main
    with:
      branch_name: ${{ github.ref }}

  lint:
    uses: omec-project/.github/.github/workflows/lint.yml@main
    with:
      branch_name: ${{ github.ref }}

  hadolint:
    uses: omec-project/.github/.github/workflows/hadolint.yml@main
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: omec-project/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: omec-project/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}

  unit-tests:
    uses: omec-project/.github/.github/workflows/unit-test.yml@main
    with:
      branch_name: ${{ github.ref }}

  e2e-tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and install dependencies
        run: |
          set -e
          sudo apt update
          sudo apt-get install -y conntrack socat ipset ebtables ansible-core
          sudo apt install -y sshpass python3-venv pipx make git
          pipx install --include-deps ansible
          pipx ensurepath
          source ~/.bashrc

      - name: Generate SSH Key
        run: |
          set -e
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N "" -q
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

      - name: Clone aether-onramp repository
        run: |
          set -e
          git clone --recursive https://github.com/opennetworkinglab/aether-onramp.git

      - name: Update files
        run: |
          set -e
          INTERFACE=$(ip route | grep default | awk '{print $5}')
          IP_ADDR=$(ip a show ${INTERFACE} | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
          echo "Extracted IP: ${IP_ADDR}"
          echo "[all]" > aether-onramp/hosts.ini
          echo "node1 ansible_host=${IP_ADDR} ansible_user=runner ansible_ssh_private_key_file=~/.ssh/id_rsa" >> aether-onramp/hosts.ini
          echo "" >> aether-onramp/hosts.ini
          echo "[master_nodes]" >> aether-onramp/hosts.ini
          echo "node1" >> aether-onramp/hosts.ini
          echo "" >> aether-onramp/hosts.ini
          echo "[worker_nodes]" >> aether-onramp/hosts.ini
          echo "" >> aether-onramp/hosts.ini
          echo "[gnbsim_nodes]" >> aether-onramp/hosts.ini
          echo "node1" >> aether-onramp/hosts.ini
          sed -i "s/ens18/eth0/" aether-onramp/vars/main.yml
          sed -i "s/10.76.28.113/${IP_ADDR}/" aether-onramp/vars/main.yml
          sed -i "s/300s/600s/" aether-onramp/deps/k8s/roles/rke2/tasks/install.yml
          sed -i '99d' aether-onramp/deps/k8s/roles/rke2/tasks/install.yml
          sed -i "s/2m30s/10m/" aether-onramp/deps/5gc/roles/core/tasks/install.yml

      - name: Test aether-pingall
        working-directory: aether-onramp
        run: |
          set -e
          make aether-pingall

      - name: Install aether-k8s
        working-directory: aether-onramp
        run: |
          set -e
          make aether-k8s-install

      - name: Install 5G Core
        working-directory: aether-onramp
        run: |
          set -e
          make aether-5gc-install

      - name: Patch K8s Deployment to attach local image
        run: |
          set -ex
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          REPO_URL="https://github.com/omec-project/${REPO_NAME}"
          git clone ${REPO_URL} ${REPO_NAME} && cd ${REPO_NAME}
          PR_NUMBER=$(echo "${GITHUB_REF}" | awk -F'/' '{print $3}')
          git fetch origin pull/${PR_NUMBER}/merge:pr-${PR_NUMBER}
          git checkout pr-${PR_NUMBER}
          if [ "${REPO_NAME}" = "webconsole" ]; then
            REPO_NAME="webui"
          fi
          docker build -t ${REPO_NAME}:testing .
          kubectl set image deployment/${REPO_NAME} ${REPO_NAME}=${REPO_NAME}:testing -n aether-5gc
          kubectl -n aether-5gc patch deployment ${REPO_NAME} \
          -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"${REPO_NAME}\",\"image\":\"${REPO_NAME}:testing\",\"imagePullPolicy\":\"Never\"}]}}}}"}'

      - name: Install GNBSIM
        working-directory: aether-onramp
        run: |
          make aether-gnbsim-install

      - name: Perform tests
        working-directory: aether-onramp
        run: |
          make aether-gnbsim-run

      - name: Validate results
        working-directory: aether-onramp
        run: |
          status=$(docker exec gnbsim-1 cat summary.log)
          if echo "$status" | grep -q "Profile Status: FAIL"; then
            echo "Profile Status indicates failure."
            exit 1
          else
            echo "Profile Status is successful."
          fi


