# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: gatici/.github/.github/workflows/build.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  docker-build:
    uses: gatici/.github/.github/workflows/docker-build.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  static-analysis:
    uses: gatici/.github/.github/workflows/static-analysis.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  lint:
    uses: gatici/.github/.github/workflows/lint.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  hadolint:
    uses: gatici/.github/.github/workflows/hadolint.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: gatici/.github/.github/workflows/license-check.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: gatici/.github/.github/workflows/fossa-scan.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}

  unit-tests:
    uses: gatici/.github/.github/workflows/unit-test.yml@add-workflows
    with:
      branch_name: ${{ github.ref }}