# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: GitHub release and Docker images

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  push-images:
    with:

  tag-github:

  release-image:
    needs: tag-github

  update-version:
    needs: tag-github

  branch-release:
    needs: tag-github