# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Stale issue/pr

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    uses: gatici/.github/.github/workflows/stale-issue.yml@add-workflows
    with:
      days_before_stale: 120
      days_before_close: 15
      cron_schedule: "0 0 * * *"
    secrets: inherit

